@startuml
!include styleClass.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam ClassHeaderBackgroundColor MODEL_COLOR

Class Patient {
name: Name
phone: Phone
email: Email
gender: Gender
icNumber: IcNumber
birthday: Birthday
age: Age
address: Address
priority: Priority
assignedDepartment: AssignedDepartment
record: Record
}

AddressBook *-right-> "1" UniquePatientList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePatientList
UniqueTagList -[hidden]down- UniquePatientList

UniqueTagList -right-> "*" Tag
UniquePatientList -right-> Patient

Patient -up-> "*" Tag
@enduml
