@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "r:RedoCommand" as RedoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":VersionedAddressBook" as VersionedAddressBook MODEL_COLOR
end box
[-> LogicManager : execute(redo)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(redo)
activate AddressBookParser

create RedoCommand
AddressBookParser -> RedoCommand
activate RedoCommand

RedoCommand --> AddressBookParser
deactivate RedoCommand

AddressBookParser --> LogicManager : r
deactivate AddressBookParser

LogicManager -> RedoCommand : execute()
activate RedoCommand

RedoCommand -> Model : redoAddressBook()
activate Model

Model -> AddressBook : resetData()
activate AddressBook
AddressBook -> Model
deactivate AddressBook

Model -> VersionedAddressBook : getNextCommand()
activate VersionedAddressBook
VersionedAddressBook -> Model : nextCommand
Model -> RedoCommand : nextCommand
deactivate VersionedAddressBook
deactivate Model

RedoCommand --> LogicManager : result
deactivate RedoCommand
RedoCommand -[hidden]-> LogicManager : result
destroy RedoCommand

[<--LogicManager
deactivate LogicManager
@enduml
